steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/comfyui-wan-i2v:latest',
    '--build-arg', 'MODEL_BUCKET=$_MODEL_BUCKET',
    '.'
  ]
  id: 'Build'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/comfyui-wan-i2v:latest']
  id: 'Push'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', 'wan-native-container',
    '--image', 'gcr.io/$PROJECT_ID/comfyui-wan-i2v:latest',
    '--region', 'us-east1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--set-env-vars', 'OUTPUT_BUCKET=$_OUTPUT_BUCKET'
  ]
  id: 'Deploy'

images:
- 'gcr.io/$PROJECT_ID/comfyui-wan-i2v:latest'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _MODEL_BUCKET: 'wan-ai-models'
  _OUTPUT_BUCKET: 'wan-ai-outputs'

