steps:
# Step 1: Download all models from GCS to a local directory ('./temp_models_gcs')
# This step runs with Cloud Build's permissions.
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'gs://wan-ai-models/*', './temp_models_gcs/']
  id: 'Download Models'

# Step 2: Build the Docker image, now that models are available locally.
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/comfyui-wan-i2v:latest',
    '.'
  ]
  id: 'Build'
  waitFor: ['Download Models'] # Wait for Step 1 to complete

# Step 3: Push the image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/comfyui-wan-i2v:latest']
  id: 'Push'

# Step 4: Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', 'wan-native-container',
    '--image', 'gcr.io/$PROJECT_ID/comfyui-wan-i2v:latest',
    '--region', 'us-east1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--set-env-vars', 'OUTPUT_BUCKET=$_OUTPUT_BUCKET'
  ]
  id: 'Deploy'

images:
- 'gcr.io/$PROJECT_ID/comfyui-wan-i2v:latest'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _OUTPUT_BUCKET: 'wan-ai-outputs'

