steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/comfyui-wan-i2v:latest', '.']
images:
- 'gcr.io/$PROJECT_ID/comfyui-wan-i2v:latest'
options:
  logging: CLOUD_LOGGING_ONLY 